colab:
  root: /content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/beginner_project
  data_yaml: ${colab.root}data/train/data.yaml
  yolov8: ${colab.root}models/yolov8n.pt

local:
  root: /Users/eojin-kim/Documents/ai_project/beginner_project/
  data_yaml: ${local.root}data/train/data.yaml
  yolov8: ${local.root}models/yolov8n.pt

train:
  epochs: 30
  imgsz: 640
  batch: 16
