colab:
  root: /content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/beginner_project
  data_yaml: ${colab.root}/data/data.yaml
  yolov8: ${colab.root}/models/yolov8n.pt
  project: /content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/beginner_project/checkpoints

local:
  root: /Users/eojin-kim/Documents/ai_project/beginner_project
  data_yaml: ${local.root}/data/data.yaml
  yolov8: ${local.root}/models/yolov8n.pt

train:
  epochs: 100
  imgsz: 640
  batch: 16
  cache: ram
  seed: 42
  multi_scale: True
  close_mosaic: 10
  lr0: 1e-5
  lrf: 1e-2
  hsv_v: 0.5
  hsv_s: 0.5
  hsv_h: 0.5

val:
  best_pt: /content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/beginner_project/checkpoints/grid_search/lr0_0.0001_lrf_0.01_batch_16/train2/weights/best.pt
  batch: 8
  imgsz: 640
 